### ISSUE TITLE
Support path component from OAS 3 'servers'

### ISSUE THREAD

**Issue by jcoyne** [interagent/committee#251]
For example my spec.json has a section like this:

```json
  "servers": [
    {
      "url": "https://dor-services-{env}.stanford.edu/{version}",
      "description": "Production service",
      "variables": {
        "env": {
          "default": "prod"
        },
        "version": {
          "default": "v1"
        }
      }
    }
]
```

so my `paths` section has keys like this: `"/objects/{id}"` and those are on the server at `/v1/objects/{id}`.  Currently with this config, the committee middleware will give a 404 response with this body:
```
"{\"id\":\"not_found\",\"message\":\"That request method and path combination isn't defined.\"}"
```

**Comment by ahx** [comment]
One question that probably has to be answered to support this:
If there are multiple servers specified, what server should be used when testing / on production / ?

I have had a similar use case as described by @jcoyne but in the end I decided to use something like `/v1/objects/{id}` in the API description instead of server url variables, but because I could not find a simple way to do this.

AFAIK the [prism](https://github.com/stoplightio/prism) mock server decided to not support this, because of the increased complexity and the differences between test/staging/production.

**Comment by ota42y** [comment]
I want to support this because it is in the definition of OpenAPI
But how to verify is difficult.

In this case, we want to select one server and make an error when the request isn't it.
(ahx said)

```
servers:
- url: https://development.gigantic-server.com/v1
  description: Development server
- url: https://staging.gigantic-server.com/v1
  description: Staging server
```

But in this case, we validate all servers and if any one matches, it should be correct.
```
servers:
- url: https://gigantic-server.com/v1
  description: Production server
- url: https://internal.gigantic-server.com:{port}/v1
  description: Internal server
  variables:
    port:
      enum:
        - '8443'
        - '443'
      default: '8443'
```
So `https://gigantic-server.com/v1` and `https://internal.gigantic-server.com:8443/v1` and `https://internal.gigantic-server.com:443/v1` is correct

Now the OpenAPI 3 definition dose not provide validation method for `servers` :(
So `committee` must define validation rule...

I think we can add option, and we can pass valid servers for this option like this.

```ruby
open_api = OpenAPIParser.parse(YAML.load_file('open_api_3/schema.yaml'))
valid_servers = [ open_api.servers[0], open_api.servers[1] ]
valid_servers = [ open_api.servers[2] ] if env['ENV'] == "dev" # use development server

schema = Committee::Drivers::OpenAPI3::Driver.new.parse(open_api, valid_servers: valid_servers)
use Committee::Middleware::RequestValidation, schema: schema
```

In this case, when the request dose not be matched 1st and 2nd definition, committee return error.

However it's big change... and in the case ( by jcoyne), I think it is faster by using `prefix` optionjcoyne.
