### ISSUE TITLE
No support for explode field in array query parameters

### ISSUE THREAD

**Issue by shike99** [interagent/committee#253]
For example, an optional query parameter of a string value, allowing multiple values by repeating the query parameter:
```
/path:
  get:
    parameters:
      - name: id
        in: query
        description: ID of the object to fetch
        schema:
          type: array
          items:
            type: integer
        explode: false
```

so this will be interpreted as `/path?id=1,2,3`, but the committee middleware will give a 400 response with this body:

`"{\"type\":\"bad_request\",\"message\":\"#/paths/~1path/get/parameters/2/schema expected array, but received String: 635\"}"`

This is the specification of OpenAPI.
https://swagger.io/docs/specification/serialization/#query
https://spec.openapis.org/oas/v3.0.2#fixed-fields-9

**Comment by shike99** [comment]
When it has no `explode` option (so the given path: `/path?id=1&id=2&id=3`), the committee middleware will still give a 400 response with same body.

**Comment by mnj93** [comment]
I'm  facing this same issue while trying to validate inputs for an array but it's not working and I'm getting following error:
```
{
    "id": "bad_request",
    "message": "#/paths/~1api~1v1~1orders/get/parameters/2/schema expected array, but received String: a,b"
}
```

@shike99 did you fix this one or using any other alternative for this one?

**Comment by shike99** [comment]
@mnj93 
I used the other alternative like this.

## swagger.yml

```
/path:
  get:
    parameters:
      - name: ids
        in: query
        description: ID of the object to fetch
        schema:
          type: string
          example: 1,2,3
```

## Rails application

For example, in a controller:
```
class TestController < ApplicationController
  def index
    ids = params[:ids].split(',') # ids => [1, 2, 3]
  end
end
```
