### ISSUE TITLE
Cannot assert on actual headers: Rack mutates header key

### ISSUE THREAD

**Issue by adsteel** [interagent/committee#262]
Given an OpenApi3 swagger yaml definition for a header:

```yaml
x-Role: &Role
  in: "header"
  name: "Role"
  required: true
  schema:
    type: "string"
    enum: ["A", "B"]
```

And given a valid request:

```bash
curl ... -H "Role: A"
```

Committee, when raising an error, raises the following error for this request:

```ruby
Committee::InvalidRequest:
       #/paths/... missing required parameters: Role
```

This is because Rack mutates all http headers, and `Role` becomes `HTTP_ROLE`.

This would seem unrelated to this gem, except that it is designed as Rack middleware, so it seems odd that it wouldn't work with rack conventions.

I'm not too familiar with the gem yet, but a first idea for a solution might be to cast all swagger-defined headers into `HTTP_x` formats before passing to validation.
