### ISSUE TITLE
Unknown param does not trigger error

### ISSUE THREAD

**Issue by adsteel** [interagent/committee#263]
Given the request validation middleware is enabled

```ruby
use(
  Committee::Middleware::RequestValidation,
  schema_path: '...',
  strict: true,
  raise: true
)
```

And a route with one defined param:

```yaml
/myroute:
  post:
    parameters:
      - in: "body"
        name: "only_param"
        required: true
```

When I make an invalid request:

```bash
curl -X POST -d only_param="a" invalid_param="b"
```

No error is raised. The readme example shows that an error should be raised or returned, depending on the configuration.
