### ISSUE TITLE
OpenAPI 3: "attribute does not allow null values"

### ISSUE THREAD

**Issue by kurko** [interagent/committee#270]
**tl;dr** I have a property with type `string` or `null`. However, on a response where said property is `null`, I get an error.

I have an OpenAPI spec that looks like this:

```yaml
components:
  schemas:
    Person-Attributes:
      title: Person Attributes
      type: object
      properties:
        name:
          type: string
        endDate:
          type:
            - string
            - 'null'
```

In a response, when `endDate` is null, I get the following error:

```rb
{
  "id"=>"invalid_response", 
  "message"=>"#/components/schemas/Person-Attributes/properties/someAttribute does not allow null values"
}
```

I've tried removing `- string` and leaving only `- 'null'`, and the error persists. I'm considering that null types are being ignored.

Is it's a known bug? Any direction on how to fix it? I can open a PR if you give me some direction.
