### ISSUE TITLE
Request validation does not support nested query parameters

### ISSUE THREAD

**Issue by gburgett** [interagent/committee#327]
First, thank you so much for building an amazing library!  It has helped us a lot in development of our new API, since we started with a documentation-driven approach.  It allows us to ensure our implementation matches our spec.  Please forgive me if this is a duplicate but I couldn't find it in your issue history.

We have some query parameters for an index operation that are defined as "filters" with a nested key for the attribute being filtered on.  An example is `GET /api/v1/events?filter[slug]=%2Ftest`.  [Rack's Query Parser implementation](https://github.com/rack/rack/blob/8be612ab949cf2eba7f4231ef17052a68315f911/lib/rack/query_parser.rb) turns the above into this params hash:
```ruby
{
  "rack.request.query_hash"=>{
    "filter"=>{
      "slug"=>"/test"
    }
  }
}
```

And then we get the following validation error:

```
#/paths/~1events/get missing required parameters: filter[slug]
```

Since it is a Rack specific behavior I didn't think this issue belonged in the `openapi_parser` library.

Thanks again!

**Comment by ota42y** [comment]
Thank you for reporting!
A little more question, how do you describe the parameters in the OpenAPI definition?
Since there is a `style: deepObject` in the Parameter Object of OpenAPi 3, it may be possible to express it.
(If this example is intended and validation fails, it's a bug)
https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#style-examples


```
paths:
  /events:
    get:
      parameters:
      - name: filter[slug]
        in: query
		style: deepObject
		explode: true
        schema:  
          type: object
		  properties:
		  	filter:
			  type: string

```
