### ISSUE TITLE
$ref with JSON pointer containing `~1` (encoded `/`) not supported

### ISSUE THREAD

**Issue by hiddewie** [interagent/committee#336]
I have document with a `$ref` for an operation of the form
```yaml
openapi: 3.0.1
# ...
paths:
  /resource/test:
    $ref: `file.yaml#/paths/~1resource~1test`
```
and `file.yaml` contains
```yaml
paths:
  /resource/test:
    summary: ... 
    description: ...
    # ...
```

Committee gives an error that the $ref is not an URI, while it is a valid URI with a fragment containing a JSON pointer.

If I make the `$ref` into something like `file.yaml#/paths/resource`, and replace the path in `file.yaml` with `resource`, it does work and Committee gives no errors.

JSON pointer spec: https://datatracker.ietf.org/doc/html/rfc6901
