### ISSUE TITLE
Query parameters: Conversion of array items does not work if parameter name ends with "[]"

### ISSUE THREAD

**Issue by ahx** [interagent/committee#369]
This is related to https://github.com/interagent/committee/issues/253

Given you have a parameter definition like this, where the name ends with a "[]", because that is a standard you've agreed on.

```yaml
parameters:
  - name: ids[]
    description: IDs of the things to get
    in: query
    schema:
      type: array
      items:
        type: integer
```

Expected behavior:
For a request like `GET /things?ids[]=1&ids=[]=2`, I would expect committee to convert the array items to integers as described in the API description. 

Current behavior:
Array items do not get converted to integers, but remain strings. 

I guess this is mostly due to Rack's default handling of "xx[]" parameters, as it handles those as "xx" array by default, so this might be tricky.

Do you plan to support this? If so I would be happy to help.
